### ISSUE TITLE
I pull down

### ISSUE THREAD

**Issue by genericuse** [TheOtherPC/Scholance#2]
Sippin' on that Henn', I know you love that Bacardi (Sonny Digital)
1942, I take you back in that 'Rari
Okay, I pull up, hop out at the after party
You and all your friends, yeah, they love to get naughty
Sippin' on that Henn', I know you love that Bacardi
1942, I take you back in that 'Rari
Switchin' lanes and I'm seein' lights, you know I watch the curb
Smokin' weed, you know I'm gettin' high, you know it calm my nerves
Trappin' hard, pumpin' non-stop, the bag I had to earn
You can try, but you might fail again, you know you never learn
Came in with a bottle, I was trippin'
And I took a couple shots and now I'm dizzy
It got me burning up, burning up
Insides burning up, burning up (yeah)
Okay, I pull up, hop out at the after party
You and all your friends, yeah, they love to get naughty
Sippin' on that Henn', I know you love that Bacardi
1942, I take you back in that 'Rari
Okay, I pull up, hop out at the after party
You and all your friends, yeah, they love to get naughty
Sippin' on that Henn', I know you love that Bacardi
1942, I take you back in that 'Rari
Uh, poppin' meds (uh), out in the meadows (yeah)
She like a little red (uh), in her stilettos (yeah)
Anytime you live (uh), out in the ghetto (yeah)
You try to duck the feds (uh), they need to let go
Came in with a bottle, I was trippin'
And I took a couple shots, it got me dizzy
It got me burning up, burning up
Insides burning up, burning up (yeah)
Okay, I pull up, hop out at the after party
You and all your friends, yeah, they love to get naughty
Sippin' on that Henn', I know you love that Bacardi
1942, I take you back in that 'Rari
Okay, I pull up, hop out at the after party
You and all your friends, yeah, they love to get naughty
Sippin' on that Henn', I know you love that Bacardi
1942, I take you back in that 'Rari
Okay, I pull up (okay, I pull up...)
Okay, I pull up (okay, I pull up...)
Okay, I pull up (okay, I pull up...), hop out at the after party
Okay, I pull up (okay, I pull up...), hop out at the after party
Okay, I pull up (okay, I pull up...), hop out at the after party
Okay, I pull up (okay, I pull up...), hop out at the after party

**Comment by vihdutta** [comment]
Who are you.
